//resources/js/type/index.d.ts

import '@inertiajs/core';
import { ErrorBag, Errors } from '@inertiajs/core';
import { LucideIcon } from 'lucide-react';
import { ReactNode } from 'react';
import type { Config } from 'ziggy-js';

export interface Auth {
  user: User;
}

export interface BreadcrumbItem {
  title: string;
  href: string;
}

export interface NavGroup {
  title: string;
  items: NavItem[];
}

export interface NavItem {
  title: string;
  href: string;
  icon?: LucideIcon | null;
  isActive?: boolean;
}

export interface SharedData {
  name: string;
  quote: { message: string; author: string };
  auth: Auth;
  ziggy: Config & { location: string };
  [key: string]: unknown;
}

export interface User {
  id: number;
  name: string;
  email: string;
  avatar?: string;
  email_verified_at: string | null;
  created_at: string;
  updated_at: string;
  [key: string]: unknown; // This allows for additional properties...
}

import '@inertiajs/core';

export interface PageProps {
  errors?: {
    [key: string]: string;
  };
  auth?: {
    user: any | null; // Replace 'any' with your actual user type
  };
  locale?: string; // Add the 'locale' property
  // Add other common props here
}

declare module '@inertiajs/core' {
  interface App<TProps extends Record<string, any> = Record<string, unknown>> {
    props: TProps & PageProps;
  }
}

import type { Component, VNode } from 'vue';

export interface PageProps {
  auth?: {
    user?: any;
  };
  locale?: string;
  [key: string]: any;
}

export interface AppType<PageProps = any> extends Component {
  (props: {
    children?: (props: {
      Component: Component;
      key: string | number;
      props: PageProps & {
        errors: Errors & ErrorBag;
        [key: string]: any;
      };
    }) => ReactNode;
  }): VNode;
}

export interface PageProps<T extends Record<string, unknown> = Record<string, unknown>> {
  auth: {
    user: any; // Replace 'any' with the actual type of your user object
  };
  errors: Record<string, string>;
  [key: string]: any; // Add this line to allow other props
}
export interface Offer {
  id: number;
  title: string;
  slug: string;
  description: string | null;
  discount_percentage: number | null;
  discount_amount: number | null;
  start_date: string | null;
  end_date: string | null;
  is_active: boolean;
  usage_limit: number | null;
  usage_count: number;
  created_at: string;
  updated_at: string;
}

export interface PaginatedResponse<T> {
  data: T[]; // Array of your data items (e.g., MessageType, OfferType)
  links: {
    // Pagination links generated by Laravel
    first: string | null;
    last: string | null;
    prev: string | null;
    next: string | null;
  };
  meta: {
    // Pagination metadata
    current_page: number;
    from: number | null;
    last_page: number;
    links: {
      // Detailed links array (often includes page numbers)
      url: string | null;
      label: string;
      active: boolean;
    }[];
    path: string;
    per_page: number;
    to: number | null;
    total: number;
  };
}

// You might also want a simpler Link type for the Pagination component itself
export interface SimpleLink {
  url: string | null;
  label: string;
  active: boolean;
}

export type HeadManagerTitleCallback = (title: string) => string;
export type HeadManagerOnUpdate = (elements: Array<HTMLElement>) => void;
export type Key = string | number | any;
export type PageResolver = (name: string) => Component;
